version: 2

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mikenye"
  
  # Maintain dependencies for pw-feeder go modules
  - package-ecosystem: "gomod"
    directory: "/pw-feeder"
    schedule:
      interval: "daily"
    assignees:
      - "mikenye"
