---
    name: Pull Request
    
    on:
      # Enable manual running of action if necessary
      workflow_dispatch:
      # Test build/deploy on PRs to main/master
      push:
        # Only publish on push to main branch
        branches:
          - main
        # Don't trigger if it's just a documentation update
        paths-ignore:
          - '**.md'
          - '**.MD'
          - '**.yml'
          - '.gitattributes'
          - '.gitignore'
    
    jobs:
    
      tests:
        name: Update codecov
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: "go mod tidy"
            run: |
              cd pw-feeder
              go mod tidy
          - name: "go test"
            run: |
              cd pw-feeder
              go test -v -coverprofile=coverage.txt ./...
          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v3
    