---
name: Upload Release Asset

on:
  release:
    types: [published]

jobs:
  upload:
    strategy:
      matrix:
        os: [linux]
        arch: [386,amd64,arm,arm64]
    name: Upload Release Assets (linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "go mod tidy"
      run: |
        cd pw-feeder
        go mod tidy
    - name: "go test"
      run: |
        cd pw-feeder
        go test -v -race -timeout=300s -count=3 -coverprofile=coverage.txt ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
    - name: "go build"
      run: |
        cd pw-feeder
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build ./cmd/pw-feeder
        tar cJvf ../pw-feeder.${{ github.ref }}.${{ matrix.os }}.${{ matrix.arch }}.tar.xz ./pw-feeder
        rm -v ./pw-feeder


    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pw-feeder.${{ github.ref }}.${{ matrix.os }}.${{ matrix.arch }}.tar.xz
        asset_name: ./pw-feeder.${{ github.ref }}.${{ matrix.os }}.${{ matrix.arch }}.tar.xz
        tag: ${{ github.ref }}
