---
name: Upload Release Asset

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: Codecov
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.25.0'
      - name: "go mod tidy"
        run: |
          cd pw-feeder
          go mod tidy
      - name: "go generate"
        run: |
          cd pw-feeder
          go generate ./...
      - name: "go test"
        run: |
          cd pw-feeder
          go test -v -race -timeout=300s -count=3 -coverprofile=coverage.txt ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4

  upload_linux:
    name: Linux Binaries
    needs: codecov
    strategy:
      matrix:
        os: [linux]
        arch: [386,amd64,arm,arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: '>=1.25.0'
    - name: "go mod tidy"
      run: |
        cd pw-feeder
        go mod tidy
    - name: "go generate"
      run: |
        cd pw-feeder
        go generate ./...
    - name: "go build"
      run: |
        cd pw-feeder
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build ./cmd/pw-feeder
        tar cJvf ../pw-feeder.${{ github.ref_name }}.${{ matrix.os }}.${{ matrix.arch }}.tar.xz ./pw-feeder
        rm -v ./pw-feeder
    - name: Upload binaries to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} ./pw-feeder.${{ github.ref_name }}.${{ matrix.os }}.${{ matrix.arch }}.tar.xz
