# Copyright (C) 2024 Plane Watch
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of pw-feeder.
#
# pw-feeder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# pw-feeder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pw-feeder. If not, see <https://www.gnu.org/licenses/>.

---
name: Upload Release Asset

"on":
  workflow_dispatch:
  release:
    types: [published]

jobs:

  upload_linux:
    name: Linux Binaries
    strategy:
      matrix:
        os: [linux]
        arch: [386, amd64, arm, arm64]
    runs-on: ubuntu-latest
    env:
      GO_LICENSES_VERSION: v2.0.1
      RELEASE_NAME: pw-feeder.${{ github.ref_name }}
      RELEASE_PLATFORM: ${{ matrix.os }}.${{ matrix.arch }}
      RELEASE_DIR: release-${{ matrix.os }}-${{ matrix.arch }}
      TOOLS_DIR: ${{ github.workspace }}/.tools
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: '>=1.25.0'
      - name: "go mod tidy"
        run: |
          cd pw-feeder
          go mod tidy
      - name: "go generate"
        run: |
          cd pw-feeder
          go generate ./...
      - name: Install licence collector
        run: |
          mkdir -p "${TOOLS_DIR}"
          GOBIN="${TOOLS_DIR}" go install \
            "github.com/google/go-licenses/v2@${GO_LICENSES_VERSION}"
      - name: Build and package release
        run: |
          mkdir -p "${RELEASE_DIR}"
          cd pw-feeder
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
            go build -o "../${RELEASE_DIR}/pw-feeder" ./cmd/pw-feeder
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
            "${TOOLS_DIR}/go-licenses" save ./cmd/pw-feeder \
            --ignore pw-feeder \
            --save_path="../${RELEASE_DIR}/THIRD_PARTY_LICENSES"

          go_root=$(go env GOROOT)
          go version -m "../${RELEASE_DIR}/pw-feeder" \
            > "../${RELEASE_DIR}/THIRD_PARTY_LICENSES/DEPENDENCIES.txt"
          mkdir -p "../${RELEASE_DIR}/THIRD_PARTY_LICENSES/go.dev"
          cp "${go_root}/LICENSE" \
            "../${RELEASE_DIR}/THIRD_PARTY_LICENSES/go.dev/LICENSE"
          cp "${go_root}/PATENTS" \
            "../${RELEASE_DIR}/THIRD_PARTY_LICENSES/go.dev/PATENTS"
          cd ..
          cp LICENSE.md "${RELEASE_DIR}/LICENSE.md"
          tar cJvf "${RELEASE_NAME}.${RELEASE_PLATFORM}.tar.xz" \
            -C "${RELEASE_DIR}" \
            pw-feeder LICENSE.md THIRD_PARTY_LICENSES
      - name: Upload binaries to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            "./${RELEASE_NAME}.${RELEASE_PLATFORM}.tar.xz"
