---
name: Upload Release Asset

on:
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: Codecov
    steps:
      - uses: actions/checkout@v4
      - name: "go mod tidy"
        run: |
          cd pw-feeder
          go mod tidy
      - name: "go test"
        run: |
          cd pw-feeder
          go test -v -race -timeout=300s -count=3 -coverprofile=coverage.txt ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  upload:
    needs: codecov
    strategy:
      matrix:
        os: [linux]
        arch: [386,amd64,arm,arm64]
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "go mod tidy"
      run: |
        cd pw-feeder
        go mod tidy
    - name: "go build"
      run: |
        cd pw-feeder
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build ./cmd/pw-feeder
        tar cJvf ../pw-feeder.${{ github.ref_name }}.${{ matrix.os }}.${{ matrix.arch }}.tar.xz ./pw-feeder
        rm -v ./pw-feeder
    - name: Upload binaries to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} ./pw-feeder.${{ github.ref_name }}.${{ matrix.os }}.${{ matrix.arch }}.tar.xz
